---

- include: packages.yml

- include: packages-debian.yml
  when: ansible_os_family == 'Debian'

- include: pip.yml
  when: mopidy_pip

- name: Mopidy conf
  ini_file:
    dest: /etc/mopidy/mopidy.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mopidy_settings }}"
  notify: restart mopidy

- name: Mopidy service
  service:
    name: mopidy
    state: started
    enabled: yes

- name: Scan local library regularly
  cron:
    name: Scan local mopidy library
    cron_file: mopidy
    user: mopidy
    special_time: "{{ mopidy_local_scan }}"
    job: mopidy --config /etc/mopidy/mopidy.conf local scan > /dev/null 2>&1
  when: mopidy_local_scan != 'never'
