---

- name: Update apt cache
  apt: update_cache=yes
  changed_when: False

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - autoconf
      - gcc
      - python-dev
    state: present
  notify: restart mopidy
